Display localized Folder name
Infomaniak/android-mail pull request #109
Opened 2022-06-17 12:46 UTC by KevinBoulongne

Depends on #108

2022-06-21 08:43 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
> +
Can you check this method please, and refactor if needed

2022-06-21 08:44 UTC, sirambd requested changes
Waiting request changes

2022-06-21 09:47 UTC, sirambd approved these changes

2022-06-23 16:47 UTC, JorisBodin approved these changes

2022-06-24 05:25 UTC, merged