#06: Add seen/unseen state in Threads list UI
Infomaniak/android-mail pull request #111
Opened 2022-06-17 12:47 UTC by KevinBoulongne

Depends on #110

2022-06-21 08:46 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
>          expeditor.text = thread.from[0].name.ifEmpty { thread.from[0].email }
use `kotlin.first`

2022-06-21 09:07 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
> +        }
Check if exists please

2022-06-21 09:08 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
> +                notifyAdapter(newList)
merge this

2022-06-21 09:09 UTC, sirambd requested changes
Waiting for request changes

2022-06-21 09:47 UTC, sirambd approved these changes

2022-06-23 16:51 UTC, JorisBodin commented on app/src/main/res/layout/item_thread.xml
> +                android:text="Display the short body when the API returns it"
Why isn't it in "tools"?

2022-06-23 16:54 UTC, JorisBodin approved these changes

2022-06-23 16:54 UTC, JorisBodin commented on app/src/main/res/layout/item_thread.xml
> +                tools:text="Expeditor name" />
Use : tools:text="@tools:sample/full_names"

2022-06-24 05:26 UTC, merged