Add listener on header to expand it on click
Infomaniak/android-mail pull request #145
Opened 2022-07-01 08:27 UTC by FabianDevel

2022-07-01 11:42 UTC, KevinBoulongne approved these changes

2022-07-12 12:13 UTC, sirambd commented on app/src/main/res/layout/item_message.xml
> +                android:layout_height="24dp"
use `marginStandard` instead of 24

2022-07-12 12:13 UTC, sirambd commented on app/src/main/res/layout/item_message.xml
> +                app:iconSize="24dp"
use `marginStandard` instead of 24

2022-07-12 12:14 UTC, sirambd commented on app/src/main/res/layout/item_message.xml
> +                android:layout_height="24dp"
use `marginStandard` instead of 24

2022-07-12 12:24 UTC, sirambd commented on app/src/main/res/layout/item_message.xml
> +                android:textSize="12sp"
use `textSmallSize` instead of `12sp`

2022-07-12 12:27 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
> +        userAvatar.setOnClickListener { onContactClicked?.invoke(from[0], isExpandedHeaderMode) }
use `from.first()` instead of `from[0]`

2022-07-12 13:27 UTC, sirambd requested changes
Waiting for request changes

2022-07-13 06:49 UTC, merged