#06: Add Login /¡\ REVIEW, BUT DON'T MERGE
Infomaniak/android-mail pull request #17
Opened 2022-05-12 11:14 UTC by KevinBoulongne

2022-05-17 16:19 UTC, JorisBodin commented on app/src/main/AndroidManifest.xml
> -        android:allowBackup="false"
If you do this, you must clearly indicate what is saved or not. Because in case of restoration it can generate bugs

2022-06-16 11:57 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
> +            GlobalScope.launch(Dispatchers.IO) {
use CoroutineScope

2022-06-16 11:58 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
> +            GlobalScope.launch(Dispatchers.IO) {
use CoroutineScope

2022-06-16 12:17 UTC, sirambd requested changes
Be careful, you should prefer `CoroutineScope` instead of `GlobalScope` unless it's really necessary.

2022-06-16 14:18 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
> +    }
Yes!

2022-06-16 14:19 UTC, closed without merging