Replace `collectOnce` with `first`
Infomaniak/android-mail pull request #172
Opened 2022-07-20 06:42 UTC by KevinBoulongne

2022-07-20 12:07 UTC, JorisBodin approved these changes

2022-07-20 13:09 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/MailData.kt
> +            val realmAddressBooks = MailRealm.readAddressBooks().first().list.toList()
I don't think that the `toList` is really needed

2022-07-20 13:26 UTC, sirambd requested changes
- [x] To simplify the code, we can use the advantages that realm offers us thanks to the `flow`, by making the database live thanks to a query as long as it's possible, and just update the database with the api, so that it automatically updates the ui.

2022-07-27 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/MailData.kt
> +            val mergedAddressBooks = mergeAddressBooks(realmAddressBooks, apiAddressBooks)
Will be done in another PR, this refactor should be global for the whole app and not just for here.

2022-07-27 07:17 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/MailData.kt
Will be done in another PR, this refactor should be global for the whole app and not just for here.

2022-07-27 07:18 UTC, merged