Thread density
Infomaniak/android-mail pull request #226
Opened 2022-08-30 08:12 UTC by LunarX

There are a few other features in this PR like last one

2022-08-31 11:40 UTC, KevinBoulongne requested changes

2022-08-31 11:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
> +        LARGE
```suggestion
        LARGE,
```

2022-08-31 11:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
> +                top ?: leftMargin,
```suggestion
                top ?: topMargin,
```

2022-08-31 11:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
> +    defStyleAttr: Int = 0
```suggestion
    defStyleAttr: Int = 0,
```

2022-08-31 11:40 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
> +                bottom ?: bottomMargin
```suggestion
                bottom ?: bottomMargin,
```

2022-08-31 14:17 UTC, JorisBodin requested changes
Waiting for changes

2022-09-06 16:43 UTC, JorisBodin approved these changes

2022-09-07 08:20 UTC, KevinBoulongne approved these changes

2022-09-07 08:20 UTC, merged