Refactor ViewModel LiveData
Infomaniak/android-mail pull request #232
Opened 2022-08-31 07:59 UTC by KevinBoulongne

2022-08-31 16:05 UTC, JorisBodin requested changes

2022-09-02 08:50 UTC, sirambd requested changes
Waiting for changes

2022-09-07 07:32 UTC, sirambd requested changes
Waiting for request changes

2022-09-07 07:32 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
> +    }
Refactor with a viewmodel

2022-09-07 07:32 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
> +                    }
Refactor with a viewmodel

2022-09-07 12:07 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
> +    }
Done in #240

2022-09-07 12:07 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
> +                    }
Done in #240

2022-09-07 12:32 UTC, merged