Realm diffutils
Infomaniak/android-mail pull request #250
Opened 2022-09-13 10:04 UTC by sirambd

Create a realm diffUtils to notify an adapter for all realm changes automatically

2022-09-13 14:20 UTC, JorisBodin approved these changes

2022-09-14 06:08 UTC, KevinBoulongne requested changes
Cannot be used as is.

We lost animations when the list is updated.

2022-09-19 12:18 UTC, sirambd commented
> 

Fixed

2022-09-19 12:20 UTC, sirambd commented
> 

Fixed, support animation for any changes with stable ids.

2022-09-20 08:34 UTC, KevinBoulongne approved these changes

2022-09-20 08:35 UTC, merged