Merge Contacts from IK & phone together + Display Recipients' avatar
Infomaniak/android-mail pull request #262
Opened 2022-09-21 15:00 UTC by LunarX

Depends on #290

2022-09-27 06:48 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +
```suggestion
```

2022-09-27 07:19 UTC, KevinBoulongne approved these changes

2022-10-04 14:07 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +        }
Move all contact related stuff in a specific util class

2022-10-04 14:15 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +    }
Delete this, move it directly in the caller

2022-10-04 14:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/models/MergedContact.kt
> +        this.id = "${email.hashCode()}_$name"
Move it to the first line

2022-10-04 15:04 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
>      fun loadAvatar(user: User): Disposable {
Re-arrange the list of these methods, putting all `loadAvatar` together

2022-10-13 16:17 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
> +        mainViewModel.updateUserInfo(this)
No need to pass the context as a parameter because the `ViewModel` can already contain it

2022-10-13 16:21 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +    fun updateUserInfo(context: Context) = viewModelScope.launch(Dispatchers.IO) {
This `ViewModel` can already have a context by changing its super class to `AndroidViewModel`.

2022-10-13 16:21 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +    private fun updateContacts(context: Context) {
Use `AndroidViewModel` instead of `ViewModel`

2022-10-17 08:36 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
> +        }
```suggestion
        val projection = arrayOf(Contactables.CONTACT_ID, Contactables.DISPLAY_NAME, Contactables.PHOTO_THUMBNAIL_URI)
        val contactCursor = context.contentResolver.query(Contactables.CONTENT_URI, projection, null, null, null)
        val contacts: MutableMap<Recipient, MergedContact> = mutableMapOf()

        contactCursor?.use { cursor ->
            while (cursor.moveToNext()) {
                val id = cursor.getLong(cursor.getColumnIndexOrThrow(Contactables.CONTACT_ID))

                if (emails.contains(id)) {
                    val name = cursor.getString(cursor.getColumnIndexOrThrow(Contactables.DISPLAY_NAME))
                    val photoUri = cursor.getString(cursor.getColumnIndexOrThrow(Contactables.PHOTO_THUMBNAIL_URI))

                    emails[id]!!.forEach { email ->
                        val key = Recipient().initLocalValues(email, name)
                        contacts[key] = MergedContact().initLocalValues(email, name, photoUri)
                    }
                }
            }
        }
```

2022-10-17 08:38 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
> +        (context.contentResolver.query(contentUri, projection, null, null, null) ?: return emptyMap()).use { cursor ->
```suggestion
        context.contentResolver.query(contentUri, projection, null, null, null)?.use { cursor ->
```

2022-10-17 09:02 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
> +    }
```suggestion
    private fun Context.getMergedEmailsContacts(
        emails: Map<Long, Set<String>>
    ): MutableMap<Recipient, MergedContact> {
        val projection = arrayOf(Contactables.CONTACT_ID, Contactables.DISPLAY_NAME, Contactables.PHOTO_THUMBNAIL_URI)
        val contacts: MutableMap<Recipient, MergedContact> = mutableMapOf()

        contentResolver.query(Contactables.CONTENT_URI, projection, null, null, null)?.use { cursor ->
            while (cursor.moveToNext()) {
                val id = cursor.getLong(cursor.getColumnIndexOrThrow(Contactables.CONTACT_ID))

                if (emails.contains(id)) {
                    val name = cursor.getString(cursor.getColumnIndexOrThrow(Contactables.DISPLAY_NAME))
                    val photoUri = cursor.getString(cursor.getColumnIndexOrThrow(Contactables.PHOTO_THUMBNAIL_URI))

                    emails[id]!!.forEach { email ->
                        val key = Recipient().initLocalValues(email, name)
                        contacts[key] = MergedContact().initLocalValues(email, name, photoUri)
                    }
                }
            }
        }

        return contacts
    }
```

2022-10-17 09:03 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
> +    }
```suggestion
    private fun Context.getLocalEmails(): Map<Long, Set<String>> {
        val mailDictionary: MutableMap<Long, MutableSet<String>> = mutableMapOf()
        val projection = arrayOf(Email.CONTACT_ID, Email.ADDRESS)
        val contentUri = Email.CONTENT_URI

        contentResolver.query(contentUri, projection, null, null, null)?.use { cursor ->
            while (cursor.moveToNext()) {
                val id = cursor.getLong(cursor.getColumnIndexOrThrow(Email.CONTACT_ID))
                val address = cursor.getString(cursor.getColumnIndexOrThrow(Email.ADDRESS))

                mailDictionary[id]?.add(address) ?: run { mailDictionary[id] = mutableSetOf(address) }
            }
        }

        return mailDictionary
    }
```

2022-10-17 09:05 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
> +            if (emails.isEmpty()) return mutableMapOf()
```suggestion
            val emails = context.getLocalEmails()
            if (emails.isEmpty()) mutableMapOf() else context.getMergedEmailsContacts(emails)
```

2022-10-18 07:51 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +        val recipient = navigationArgs.recipient
useless line

2022-10-18 12:07 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> +        contactPermissionResultLauncher = registerForActivityResult(ActivityResultContracts.RequestPermission()) { isGranted ->
init it with a lazy

2022-10-18 12:11 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +    private val viewModel: MainViewModel by activityViewModels()
rename to `mainViewModel`

2022-10-18 12:12 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +            val recipient = navigationArgs.recipient
useless line

2022-10-18 12:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +            (holder.binding as CardviewThreadItemBinding).apply {
replace `apply` with a `with`

2022-10-18 12:32 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +                expeditorAvatar.loadAvatar((dataSet[position] as Thread).from.first(), contacts)
Replace `first` by `firstOrNull`. 
And please review the logic

2022-10-18 12:33 UTC, sirambd requested changes
Waiting for request changes

2022-10-25 08:10 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
> +    }
EmbeddedObjects already exist though, right?

2022-10-25 09:31 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
> +    }
Fixed.

2022-10-26 10:23 UTC, KevinBoulongne approved these changes

2022-10-26 10:24 UTC, sirambd approved these changes

2022-10-26 10:27 UTC, merged