Add UiSettings with NightMode & ColorTheme
Infomaniak/android-mail pull request #265
Opened 2022-09-26 10:21 UTC by KevinBoulongne

2022-09-27 08:15 UTC, LunarX approved these changes

2022-09-27 15:06 UTC, JorisBodin requested changes

2022-09-27 15:06 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
>          setTheme(theme)
Use directly a property `themeRes` in `ColorTheme`

2022-09-27 15:07 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/models/UiSettings.kt
> +    enum class ColorTheme(@StringRes val localisedNameRes: Int) {
Add `themeRes`

2022-09-28 11:13 UTC, JorisBodin approved these changes

2022-09-28 11:13 UTC, merged