Styling `Manage my account`
Infomaniak/android-mail pull request #278
Opened 2022-10-04 12:23 UTC by LunarX

2022-10-11 11:48 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
> +        }
Why do you only want the IDs?

2022-10-13 07:34 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
> +        }
Indeed, it makes no sens

2022-10-14 10:15 UTC, KevinBoulongne approved these changes

2022-10-19 08:58 UTC, sirambd commented on app/src/main/res/layout/fragment_switch_user.xml
> +            app:iconPadding="8dp"
the dimension `marginStandardSmall` exists

2022-10-19 09:14 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +    private fun mailboxContentDbName(userId: Int, mailboxId: Int) = "${mailboxContentDbNamePrefix(userId)}${mailboxId}.realm"
Why did you move them here?

2022-10-19 09:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +                // .deleteRealmIfMigrationNeeded() // TODO: Do we want to keep this in production?
Put it back the way it was before, we keep them in the development phase first

2022-10-19 09:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +                // .deleteRealmIfMigrationNeeded() // TODO: Do we want to keep this in production?
Put it back the way it was before, we keep them in the development phase first

2022-10-19 09:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +                // .deleteRealmIfMigrationNeeded() // TODO: Do we want to keep this in production?
Put it back the way it was before, we keep them in the development phase first

2022-10-19 09:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +                // .deleteRealmIfMigrationNeeded() // TODO: Do we want to keep this in production?
Put it back the way it was before, we keep them in the development phase first

2022-10-19 12:52 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
> +            val typedArray = context.obtainStyledAttributes(attrs, R.styleable.SimpleSettingView, 0, 0)
use `attrs?.getAttributes`

2022-10-19 13:51 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
> +            val typedArray = context.obtainStyledAttributes(attrs, R.styleable.SimpleSettingView, 0, 0)
Fixed in #279

2022-10-19 14:13 UTC, sirambd approved these changes

2022-10-19 14:23 UTC, sirambd requested changes

2022-10-19 14:23 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
> +        binding = ViewSimpleSettingBinding.inflate(LayoutInflater.from(context), this)
use `lazy`

2022-10-25 09:17 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +        fun userInfoDbName(userId: Int) = "User-${userId}.realm"
Make it private

2022-10-25 09:18 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
> +        fun mailboxContentDbNamePrefix(userId: Int) = "Mailbox-${userId}-"
Make it private

2022-10-25 09:27 UTC, sirambd requested changes
Waiting for request changes

2022-10-27 12:10 UTC, JorisBodin approved these changes

2022-10-28 05:51 UTC, KevinBoulongne approved these changes

2022-10-28 09:18 UTC, merged