Directly go to NewMessage screen when opening a Thread that is really just 1 Draft
Infomaniak/android-mail pull request #288
Opened 2022-10-14 11:23 UTC by KevinBoulongne

Depends on #287

2022-10-26 09:42 UTC, sirambd requested changes

2022-10-26 09:42 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
>      fun executeDraftsActions() = viewModelScope.launch(Dispatchers.IO) {
Clean actions when executed

2022-10-26 10:18 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
>      fun executeDraftsActions() = viewModelScope.launch(Dispatchers.IO) {
Will be done in another PR.

2022-10-28 12:03 UTC, sirambd approved these changes

2022-10-31 15:20 UTC, merged