Swipe to delete Thread
Infomaniak/android-mail pull request #308
Opened 2022-10-21 13:05 UTC by KevinBoulongne

2022-10-24 07:26 UTC, LunarX approved these changes

2022-10-25 13:06 UTC, sirambd requested changes

2022-10-26 08:58 UTC, sirambd requested changes

2022-10-26 08:58 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
> +                return !shouldDeleteItem
Add comment to explains this

2022-10-26 08:58 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +                forceRefreshThreads(filter)
Comment to explains this

2022-10-26 10:01 UTC, merged