Reply to mail
Infomaniak/android-mail pull request #315
Opened 2022-10-31 08:41 UTC by KevinBoulongne

Depends on #314

2022-11-02 09:23 UTC, LunarX requested changes

2022-11-02 14:47 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
> +            isDraftExisting = false,
Renamed into `draftExists` in #320

2022-11-02 14:53 UTC, LunarX approved these changes

2022-11-04 16:40 UTC, JorisBodin requested changes

2022-11-04 16:40 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
>              .localUuid
You should refactor this whole part. Too many apply, let and also at the same time. It's very difficult to read.

2022-11-04 18:12 UTC, JorisBodin approved these changes

2022-11-04 18:12 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
>              .localUuid
I jsut see it : https://github.com/Infomaniak/android-mail/pull/321/files

2022-11-04 18:12 UTC, merged