Put back the `Unread` filter
Infomaniak/android-mail pull request #343
Opened 2022-11-11 14:26 UTC by KevinBoulongne

Depends on #342

2022-11-21 17:19 UTC, JorisBodin requested changes

2022-11-22 10:41 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/Utils.kt
> +    }
Because it's a general class that could be used anywhere, but since there's little chance it happens, I'll move it back to the `ThreadListViewModel`.

2022-11-23 06:37 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
>      }
Seen on kChat.

2022-11-23 10:33 UTC, JorisBodin approved these changes

2022-11-23 11:30 UTC, sirambd requested changes

2022-11-23 11:46 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
> +        if (unreadCount == 0 && lastUnreadCount > 0 && threadListViewModel.currentFilter.value != ThreadFilter.ALL) clearFilter()
True.
It's been simplified.

2022-11-23 13:14 UTC, sirambd approved these changes

2022-11-23 13:58 UTC, merged