Display signature when composing a new mail
Infomaniak/android-mail pull request #371
Opened 2022-11-25 14:27 UTC by LunarX

2022-11-25 16:04 UTC, JorisBodin requested changes

2022-11-25 16:04 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +                binding.separatedSignature.isVisible = false
isGone = true

2022-11-28 08:28 UTC, LunarX commented on app/build.gradle
> +    implementation 'org.jsoup:jsoup:1.15.3'
Tried it but ends up being way heavier to write than jsoup

2022-11-28 08:36 UTC, JorisBodin approved these changes

2022-11-28 08:36 UTC, merged