Made whole swipe setting illustration clickable
Infomaniak/android-mail pull request #412
Opened 2022-12-08 08:40 UTC by LunarX

2022-12-08 10:17 UTC, KevinBoulongne approved these changes

2022-12-13 17:05 UTC, JorisBodin requested changes

2022-12-13 17:05 UTC, JorisBodin commented on app/src/main/res/values/attrs.xml
> +        <attr name="noRipple" format="boolean" />
I would have rather put simple `ripple` with default value `true`.

2022-12-15 09:46 UTC, JorisBodin approved these changes

2022-12-15 09:46 UTC, merged