New message composition
Infomaniak/android-mail pull request #435
Opened 2022-12-21 10:43 UTC by LunarX

2022-12-22 18:39 UTC, sirambd requested changes

2022-12-22 18:39 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
> +    private fun populateViewModelWithDraftData() {
We are already in the viewmodel so I find it a bit weird, just replace viewModel with data I find it sufficient, and why `populate` instead of `init`

2022-12-22 18:39 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +        handleActionSend()
This way we can simplify it by putting everything together and avoid unnecessary operations.

2022-12-23 08:59 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
> +        return if (sorted) query.sort(MergedContact::name.name) else query
Use apply plz

2022-12-23 09:45 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
> +        binding.bccField.initRecipients(mailBcc)
We already are in a `with` scope here.

Do we want to imbricate multiples `with` ?

2022-12-23 13:19 UTC, JorisBodin approved these changes

2022-12-23 13:19 UTC, merged