Don't save Draft if there is no modification
Infomaniak/android-mail pull request #445
Opened 2023-01-02 09:52 UTC by KevinBoulongne

2023-01-02 15:12 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
> +            // mailSignature,
Remove useless comments

2023-01-02 15:39 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
> +        if (snapshot.isTheSame()) {
Rename to `hasNoChanges` instead

2023-01-02 15:41 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
> +                // signature == mailSignature &&
useless

2023-01-02 16:35 UTC, sirambd requested changes
This feature need logical changes.

2023-01-04 15:47 UTC, sirambd requested changes

2023-01-06 13:59 UTC, sirambd approved these changes

2023-01-06 15:18 UTC, JorisBodin approved these changes

2023-01-06 15:18 UTC, merged