When replying to a Thread, reply to the last received Message
Infomaniak/android-mail pull request #452
Opened 2023-01-05 15:08 UTC by KevinBoulongne

2023-01-06 15:00 UTC, sirambd requested changes

2023-01-06 15:00 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
> +                ?: it.last()
Move to the controller

2023-01-06 15:00 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
> +            fun List<Message>.getLastMessageToExecuteAction(): Message = lastOrNull { !it.isDraft } ?: last()
Use the realmList subquery

2023-01-09 12:19 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
> +            fun List<Message>.getLastMessageToExecuteAction(): Message = lastOrNull { !it.isDraft } ?: last()
Ok, will be done in another PR.

2023-01-09 15:10 UTC, sirambd approved these changes

2023-01-10 15:38 UTC, JorisBodin approved these changes

2023-01-10 15:39 UTC, merged