Refactor actions
Infomaniak/android-mail pull request #470
Opened 2023-01-11 13:19 UTC by KevinBoulongne

2023-01-12 15:26 UTC, sirambd requested changes

2023-01-12 15:26 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +            refreshFolders(mailbox, localSettings.threadMode, messagesFoldersIds)
It's useless the `val`

2023-01-12 15:26 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +            refreshFolders(mailbox, localSettings.threadMode, messagesFoldersIds)
It's useless the `val`

2023-01-12 15:26 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +            refreshFolders(mailbox, localSettings.threadMode, messagesFoldersIds)
It's useless the `val`

2023-01-16 08:58 UTC, sirambd approved these changes

2023-01-16 13:52 UTC, JorisBodin approved these changes

2023-01-16 15:05 UTC, merged