Refresh Thread when sending Draft
Infomaniak/android-mail pull request #475
Opened 2023-01-13 10:56 UTC by KevinBoulongne

2023-01-16 15:57 UTC, sirambd requested changes

2023-01-16 15:57 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +            updateFolderAfterScheduledDate(scheduledDates)
This function is called only if the list is not empty, because `isFailure` can be `true` when the list is not empty.

2023-01-16 15:57 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
> +        private const val REFRESH_DELAY = 1_500L
Add a comment to explain it

2023-01-18 13:21 UTC, JorisBodin approved these changes

2023-01-18 13:22 UTC, merged