Manage action canceling
Infomaniak/android-mail pull request #485
Opened 2023-01-17 14:23 UTC by FabianDevel

depends on #475

2023-01-23 13:48 UTC, KevinBoulongne approved these changes

2023-01-25 14:13 UTC, sirambd requested changes

2023-01-25 14:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +        val undoIds = messages.getFoldersIds(exception = undoDestinationId) + archiveId
Rename to `undoFoldersIds`

2023-01-25 14:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +        val undoIds = (messages.getFoldersIds(exception = undoDestinationId) + trashId).filterNotNull()
Rename to `undoFoldersIds`

2023-01-25 14:13 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +    }
```suggestion
    fun undoAction(undoData: UndoData) = viewModelScope.launch(Dispatchers.IO) {
        val mailbox = currentMailbox.value ?: return@launch
        val (resource, foldersIds, destinationFolderId) = undoData

        val snackbarTitle = if (ApiRepository.undoAction(resource).data == true) {
            refreshFolders(mailbox, foldersIds, destinationFolderId)
            R.string.snackbarMoveCancelled
        } else {
            RCore.string.anErrorHasOccurred
        }

        snackbarFeedback.postValue(context.getString(snackbarTitle) to null)
    }
```

2023-01-25 14:13 UTC, sirambd commented
Rename all `undoIds` with `undoFoldersIds`

2023-01-25 15:41 UTC, sirambd approved these changes

2023-01-25 15:42 UTC, JorisBodin approved these changes

2023-01-25 15:43 UTC, LunarX approved these changes

2023-01-25 15:45 UTC, merged