Merge "Message & Thread as Favorites" functions into one
Infomaniak/android-mail pull request #487
Opened 2023-01-17 15:48 UTC by FabianDevel

Depends on #486

2023-01-18 07:26 UTC, KevinBoulongne approved these changes

2023-01-24 16:41 UTC, sirambd approved these changes

2023-01-24 16:42 UTC, merged

2023-01-24 17:10 UTC, JorisBodin requested changes

2023-01-24 17:10 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +            ?: if (thread.isFavorite) thread.getFavoriteMessages() else thread.getLastMessageToExecuteAction()
I would have made a nested functions