Clean code
Infomaniak/android-mail pull request #508
Opened 2023-01-23 14:21 UTC by KevinBoulongne

2023-01-23 16:35 UTC, sirambd requested changes

2023-01-23 17:00 UTC, JorisBodin requested changes

2023-01-23 17:00 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
> -    var stUuid: String? = null
Keep it, it's for the swisstransfer feature

2023-01-23 17:00 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> +        date = messages.last { it.folderId == folderId }.date
If a thread has no message, there is a bug

2023-01-24 07:34 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> +        date = messages.last { it.folderId == folderId }.date
A thread can't have no message.

If it happens, it means we have a bug somewhere else, and we'll probably want to know it, and not fail silently.

2023-01-25 16:38 UTC, JorisBodin approved these changes

2023-01-25 16:38 UTC, merged