Display the correct Message in `SENT` folder
Infomaniak/android-mail pull request #513
Opened 2023-01-24 13:10 UTC by KevinBoulongne

2023-01-24 16:37 UTC, JorisBodin approved these changes

2023-01-25 14:15 UTC, sirambd requested changes

2023-01-25 14:15 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +    }
I'm not too convinced of that

2023-01-30 10:35 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +    }
It's been revamped.

2023-02-01 16:18 UTC, sirambd approved these changes

2023-02-01 16:18 UTC, JorisBodin approved these changes

2023-02-01 16:19 UTC, merged