Update action bottom sheet + Fix some UI
Infomaniak/android-mail pull request #514
Opened 2023-01-24 14:24 UTC by LunarX

2023-02-07 13:52 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
> +
```suggestion
```

2023-02-07 13:55 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
> +            val args = JunkBottomSheetDialogArgs(threadUid!!, messageUid).toBundle()
```suggestion
            val threadUid = it.getString(THREAD_UID)!!

            val args = JunkBottomSheetDialogArgs(threadUid, messageUid).toBundle()
```

2023-02-07 14:59 UTC, KevinBoulongne approved these changes

2023-02-07 15:48 UTC, FabianDevel requested changes

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
> +    lateinit var binding: BottomSheetJunkBinding
```suggestion
    private lateinit var binding: BottomSheetJunkBinding
```

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
>      lateinit var binding: BottomSheetActionsMenuBinding
```suggestion
    protected lateinit var binding: BottomSheetActionsMenuBinding
```

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
> +            findNavController().popBackStack()
```suggestion
            findNavController().popBackStack()
            callback()
```

Calling popBackStack after the callback will close any dialog or fragment callback could navigate to. For example the future dialog for phishing confirmation

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
> +        val messageUid = navigationArgs.messageUid
Use directly navigationArgs values without creating a val

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
> +
```suggestion

```

2023-02-07 15:48 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
> +
```suggestion

```

2023-02-07 15:55 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
> +            findNavController().popBackStack()
You can also use this with setClosingOnClickListener to navigate to JunkBottomSheet without backNavigationResults

2023-02-08 13:34 UTC, FabianDevel approved these changes

2023-02-08 13:47 UTC, JorisBodin approved these changes

2023-02-08 13:47 UTC, merged