Manage swipe actions variants
Infomaniak/android-mail pull request #582
Opened 2023-02-13 11:02 UTC by FabianDevel

- Change the icon of the favorite swipeAction when used on an already favorite thread
- Change the swipe action of _archive_, _spam_ and _read and archive_ to _move to inbox_
- Small related fixes and refactor

2023-02-20 12:52 UTC, KevinBoulongne requested changes

2023-02-20 12:52 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +    private fun updateDynamicIcons(item: Thread) {
Rename `item` into `thread`.

2023-02-20 13:46 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
> +        INBOX(R.string.actionMoveToInbox, R.color.swipeInbox, R.drawable.ic_drawer_inbox),
Finally, it's been removed.

2023-02-20 13:55 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
> +        }
Extract this in a `setArchiveUi()` method like the other actions that change Ui

2023-02-20 14:42 UTC, LunarX approved these changes

2023-02-21 10:25 UTC, KevinBoulongne approved these changes

2023-02-23 11:01 UTC, JorisBodin approved these changes

2023-02-23 11:01 UTC, merged