Add unknown recipient button when composing new message
Infomaniak/android-mail pull request #601
Opened 2023-02-16 13:10 UTC by LunarX

2023-02-16 14:59 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
> +                    else setSnackBar(R.string.addUnknownRecipientInvalidEmail)
Add braces.

2023-02-16 15:00 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
> +                setSnackBar = { setSnackBar(it) }
```suggestion
                setSnackBar = { setSnackBar(it) },
```

2023-02-16 15:02 UTC, KevinBoulongne commented on app/src/main/res/drawable/ic_unknown_user_avatar.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Add header.

2023-02-16 15:03 UTC, KevinBoulongne commented on app/src/main/res/values-fr/strings.xml
> +    <string name="onBoardingTitle1">Choisissez une couleur d\'accentuation,\nrose ou bleu ?</string>
```suggestion
    <string name="onBoardingTitle1">Choisissez une couleur d’accentuation,\nrose ou bleu ?</string>
```

2023-02-16 15:04 UTC, KevinBoulongne commented on app/src/main/res/values-fr/strings.xml
> +    <string name="addUnknownRecipientAlreadyUsed">L\'adresse mail est déjà utilisée</string>
Use `’`.

Modify it on Loco too.

2023-02-16 15:04 UTC, KevinBoulongne commented on app/src/main/res/values-fr/strings.xml
> +    <string name="addUnknownRecipientInvalidEmail">L\'adresse mail n\'est pas valide</string>
Use `’`.

Modify it on Loco too.

2023-02-16 15:08 UTC, KevinBoulongne requested changes

2023-02-17 07:45 UTC, KevinBoulongne approved these changes

2023-02-17 11:11 UTC, JorisBodin approved these changes

2023-02-17 11:12 UTC, merged