Adds search UI
Infomaniak/android-mail pull request #625
Opened 2023-02-22 13:07 UTC by LunarX

Depends on #624 

Is missing:
* Wrong empty state illustration for search results
* Pagination
* Swipe refresh on search results to query again
* Swipe actions
* History is implemented in the next PR

Observation:
* There's no ui indication if the search is offline/online ?

2023-02-24 13:51 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
> +    fun message(messageUid: String) = liveData(coroutineContext) {
rename to `getFolderIdByMessage`

2023-02-24 13:52 UTC, sirambd commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
> +    fun thread(threadUid: String) = liveData(coroutineContext) {
rename to `getFolderIdByThread`

2023-02-24 14:26 UTC, KevinBoulongne requested changes

2023-02-24 14:26 UTC, KevinBoulongne commented on app/src/main/res/layout/item_search_folder.xml
> +
```suggestion
```

2023-02-24 14:26 UTC, KevinBoulongne commented on app/src/main/res/layout/fragment_search.xml
> +
```suggestion
```

2023-02-24 17:07 UTC, JorisBodin requested changes

2023-02-27 13:39 UTC, FabianDevel requested changes

2023-02-27 13:39 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
> +    }
Put this function in Extension.kt

2023-02-27 14:21 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
> +        folderDropDown.setOnClickListener { popupMenu.show() }
It creates it once when setting the ui and then shows it as many times as necessary when clicked

2023-02-27 14:41 UTC, FabianDevel commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
> +        folderDropDown.setOnClickListener { popupMenu.show() }
true, I read too fast

2023-02-27 15:03 UTC, FabianDevel approved these changes

2023-02-27 15:09 UTC, JorisBodin approved these changes

2023-02-27 15:15 UTC, merged