Add custom pagination for the search
Infomaniak/android-mail pull request #632
Opened 2023-02-23 08:24 UTC by LunarX

Depends on #627

2023-02-24 13:05 UTC, KevinBoulongne requested changes

2023-02-24 13:05 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
> +    companion object {
```suggestion
    private companion object {
```

2023-02-24 16:34 UTC, JorisBodin approved these changes

2023-02-27 15:14 UTC, KevinBoulongne requested changes

2023-02-27 15:14 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
> +    private val hasNextPage get() = !resourceNext.isNullOrBlank()
This will conflict.

2023-02-27 15:18 UTC, merged