Add New contact to address book
Infomaniak/android-mail pull request #637
Opened 2023-02-23 10:32 UTC by FabianDevel

Depends on #634 

The listeners ending with `popBackStack()` will be factorized in the next PR

2023-02-23 14:56 UTC, KevinBoulongne requested changes

2023-02-23 14:56 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
> +    fun contacts() = "${contact()}/all?with=emails,details,others,contacted_times"
```suggestion
    fun contact() = "$MAIL_API/api/pim/contact"

    fun contacts() = "${contact()}/all?with=emails,details,others,contacted_times"
```

2023-02-23 14:56 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +        detailedContactViewModel.snackBarManager.setup(activity, getAnchor = { activity.findViewById(R.id.quickActionBar) })
```suggestion
    private fun setupSnackBar() = with(requireActivity()) {
        detailedContactViewModel.snackBarManager.setup(this, getAnchor = { findViewById(R.id.quickActionBar) })
```

2023-02-24 10:39 UTC, JorisBodin requested changes

2023-02-24 10:39 UTC, JorisBodin commented on app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
> +    fun computeFirstAndLastName(): Pair<String, String> {
Refactor with `computeInitials`

2023-02-24 12:43 UTC, LunarX commented on app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
> +    fun computeFirstAndLastName(): Pair<String, String> {
We should coordinate with iOS

2023-02-28 13:27 UTC, KevinBoulongne approved these changes

2023-03-01 14:11 UTC, KevinBoulongne requested changes

2023-03-01 14:11 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
> +        val snackbarTitle = if (apiResponse.isSuccess()) {
```suggestion

        val isSuccess = ApiRepository.addContact(AddressBookController.getDefaultAddressBook().id, recipient).isSuccess()

        val snackbarTitle = if (isSuccess) {
```

2023-03-01 14:11 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
> +    private fun setupListeners() = with(binding) {
```suggestion
    private fun setupListeners() = with(binding) {

```

2023-03-01 14:15 UTC, KevinBoulongne approved these changes

2023-03-01 17:22 UTC, JorisBodin approved these changes

2023-03-01 17:22 UTC, merged