Update create folder dialog
Infomaniak/android-mail pull request #655
Opened 2023-03-01 08:37 UTC by FabianDevel

Update the folder creation dialog with the maquetted button's color and add error handling by the textInputLayout

2023-03-01 15:41 UTC, KevinBoulongne requested changes

2023-03-02 07:23 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
> +    protected fun checkForFolderCreationErrors(folderName: CharSequence): String? {
It's been checked with them, they'll fix this in the future.

2023-03-02 08:08 UTC, KevinBoulongne approved these changes

2023-03-02 08:35 UTC, LunarX approved these changes

2023-03-02 12:52 UTC, merged