Firebase messaging
Infomaniak/android-mail pull request #666
Opened 2023-03-02 10:58 UTC by sirambd

**News**
- feat: Add 2 flavors (`standard`: with play services, `fdroid`: without play services)
- feat: (`standard flavor`) - Handle firebase cloud messaging if play services is available
- feat: (`standard flavor`) - Register the user device for firebase push notifications if `play service` is available
- feat: (`standard flavor`) - Process firebase push notifications in foreground, (notify threadList if needed)
- feat: (`standard flavor`) - Process firebase push notifications in background, (show notification)
- feat: (`standard flavor`) - Keep sync messages worker every 15 min
- feat: (`fdroid flavor`)  - Without play service, the sync is done every 15 min with sync worker

2023-03-02 17:50 UTC, JorisBodin requested changes

2023-03-02 17:50 UTC, JorisBodin commented on app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
> +            Toast.makeText(this, "need play services", Toast.LENGTH_SHORT).show()
It must be translated

2023-03-03 10:55 UTC, JorisBodin approved these changes

2023-03-03 13:28 UTC, KevinBoulongne requested changes

2023-03-03 13:28 UTC, KevinBoulongne commented on app/build.gradle
> +            }
```suggestion
            getIsDefault().set(true)
            dependencies { implementation 'com.google.firebase:firebase-messaging-ktx:23.1.1' }
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/build.gradle
> +    productFlavors {
```suggestion

    productFlavors {
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/fdroid/java/com/infomaniak/mail/GplayExtensions.kt
> +fun Context.cancelFirebaseProcessWorks() = Unit
```suggestion
fun Context.cancelFirebaseProcessWorks() = Unit

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/fdroid/java/com/infomaniak/mail/firebase/RegisterFirebaseBroadcastReceiver.kt
> +class RegisterFirebaseBroadcastReceiver : IRegisterFirebaseBroadcastReceiver
```suggestion
class RegisterFirebaseBroadcastReceiver : IRegisterFirebaseBroadcastReceiver

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
> +
```suggestion
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +        okHttpClient: OkHttpClient
```suggestion
        okHttpClient: OkHttpClient,
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
> +        // Show group summary notification
```suggestion

        // Show group summary notification
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/utils/IRegisterFirebaseBroadcastReceiver.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
> +        /** To support the old services, we do not change the name */
```suggestion

        /** To support the old services, we do not change the name */
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
> +            Toast.makeText(this, "need play services", Toast.LENGTH_SHORT).show()
```suggestion
            // TODO: Translate this
            Toast.makeText(this, "Need Play Services", Toast.LENGTH_SHORT).show()
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
> +    val localSettings = LocalSettings.getInstance(context)
```suggestion

    val localSettings = LocalSettings.getInstance(context)
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/FirebaseApiRepository.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
> +            // Ignore if the mailbox notification channel is blocked
```suggestion
            // Ignore if the Mailbox notification channel is blocked
```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/RegisterFirebaseBroadcastReceiver.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/RegistrationInfos.kt
> +}
```suggestion
}

```

2023-03-03 13:28 UTC, KevinBoulongne commented on app/src/standard/java/com/infomaniak/mail/firebase/RegistrationInfos.kt
> +        private fun getDeviceName(contentResolver: ContentResolver): String {
```suggestion
        const val OS_NAME = "android"
        val DEVICE_MODEL: String = android.os.Build.MODEL

        fun getDeviceName(contentResolver: ContentResolver): String {
```

2023-03-03 13:46 UTC, KevinBoulongne approved these changes

2023-03-03 13:46 UTC, merged