Remove unused variable
Infomaniak/android-mail pull request #683
Opened 2023-03-07 14:43 UTC by LunarX

2023-03-07 15:13 UTC, KevinBoulongne requested changes

2023-03-07 15:13 UTC, KevinBoulongne commented on app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
> -        ALL(R.string.searchAllMessages),
Remove this string too.

2023-03-08 06:39 UTC, KevinBoulongne approved these changes

2023-03-08 07:09 UTC, FabianDevel approved these changes

2023-03-08 07:09 UTC, merged